# Generated by Django 3.1.7 on 2021-02-28 10:09

import apps.document.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_created=True)),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('original_document', models.ImageField(upload_to='pdf_document/%Y/%m/%d', validators=[apps.document.validators.validate_pdf_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('page', models.ImageField(upload_to='pdf_page')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='document.pdfdocument')),
            ],
        ),
    ]
