# Generated by Django 3.1.7 on 2021-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='date_failed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
