# Generated by Django 3.1.7 on 2021-03-06 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_pdfdocument_date_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='original_document',
            field=models.FileField(upload_to='pdf_document/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
